apiVersion: v1
kind: Service
metadata:
  name: akka-hello-world
  namespace: multi-app
spec:
  type: NodePort
  selector:
    app: akka-hello-world
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP 