apiVersion: v1
kind: Service
metadata:
  name: java-webapp
  namespace: multi-app
spec:
  type: NodePort
  selector:
    app: java-webapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP 